name: flutter_button
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/garbanzos.png
  - assets/judiasverdes.jpg
  - assets/lentejas.png
  - assets/naranja.png
  - assets/nombreGym.jpg
  - assets/pavo.png
  - assets/rutinaAbdominales.jpg
  - assets/rutinaEspalda.jpg
  - assets/rutinaHombros.jpg
  - assets/rutinaPecho.jpg
  - assets/rutinaPierna.jpg
  
